### ISSUE TITLE
Don't show repeated quotes

### ISSUE THREAD

**Issue by matootie** [yoiksoft/philosopher#1]
Prevent one user from seeing a quote that they've seen before.

**Comment by matootie** [comment]
### Ok I've been wrestling with a way to make quote requests unique and... I think I have a solution but it's kind of weird...

So right now when you make a request to get some quotes to vote on, the back-end runs Redis' `SRANDMEMBER` command which gets random members of a set. Runtime is _O(2)_ for two members. The system also does some other stuff so realistically it's like _O(5)_ or something but basically... it's very fast. This method doesn't ensure any uniqueness at all though, so I was thinking about how to do that.

### The first idea

Well, the first thing I thought of was to also store a set of the quotes that the user has seen before, then calculate the difference between set of all quotes and the set of seen quotes, and pull random from that. But this is very expensive. It ends up being best case _O(n)_ where n is the number of quotes that are submitted, and worst case _O(2n)_ as your seen quotes approaches the same cardinality as the submitted quotes. **Very very bad if we have lots of users and lots of quotes**.

### The second idea

The second thing I considered was duping the set of all quotes for the user and popping two off when you're going to vote so they just won't be in the set anymore. This keeps runtime fast when getting quotes to vote on but the duping process is _O(n)_ and even worse it gets very complicated when people try to submit a new quote because then we have to add it to each users set somehow. **Not really feasible with many users**.

### The solution... I think

The solution I think I've landed on is to just forget about ensuring unique results straight out of the database. What's gonna happen is the system will still use `SRANDMEMBER`, then it will store those in a set representing quotes the user has already seen. The result is cached like we have right now so further requests (before submitting a vote) will always return the same quotes. If the results from `SRANDMEMBER` appear in the set of quotes the user has already seen (using command `SISMEMBER`, _O(2)_ when checking both quotes) then the back-end will return the _"There aren't enough quotes in the db"_ response, but it will initiate a background tasks wherein it will go and keep trying new random quotes until it finds a new unique match.

**I know what you're thinking...** this sounds awful. But it's actually not that bad. Hear me out.

With that solution, what ends up happening is requests are continuously made to the database until some flag to stop comes up. The requests to the database are all made asynchronously so it doesn't block new requests at all. Effectively, at it's worst it will be as if every single user is constantly requesting new quotes to vote on, _which we should be able to handle anyways right?_ If the cardinality of the set of quotes a user has seen is equal or greater than the cardinality of the set of quotes that have been submitted (`SCARD` command, _O(2)_ when checking both sets), it means the user has seen all and the background task will stop. If the day ends, the background task will stop. If it finds a match, the background task will stop and the result is cached so next time the user requests quotes to vote on it will just grab from cache instead of going through the whole process again.

Here's kind of a strange example
```python
def fetch_in_background(day, user_id):

  # Keep going until we have unique or a stop flag.
  while True:

    # If it's a new day...
    if day < today:
      # Stop the background task.
      return

    # Get the cardinality of both sets.
    num_quotes = await redis.scard(f"{day}:quotes")
    num_seen = await redis.scard(f"{day}:seen:{user_id}")

    # If user has already seen all quotes...
    if num_seen >= num_quotes:
      # Stop the background task.
      return
    
    # Get two random quotes.
    quotes = await redis.srandmember(f"{day}:quotes", 2)

    # Determine if the user has seen either quote.
    has_seen_a = await redis.sismember(f"{day}:seen:{user_id}", quotes[0])
    has_seen_b = await redis.sismember(f"{day}:seen:{user_id}", quotes[1])

    # If the user has not seen either quote...
    if not has_seen_a and not has_seen_b:
      # Cache the result
      await redis.rpush(f"{day}:request:{user_id}", *quotes)

      # Add the quotes to seen.
      await redis.sadd(f"{day}:seen:{user_id}", *quotes)
      
      # Stop the background task
      return
   
    # Otherwise, go again.
```

Some notes:
- The system will not start another background task to continuously fetch quotes if there is already a background task that is not done yet. We'll do this by setting a specific value in the DB and check for it before launching a background task.
- The example code above isn't exactly as it will be implemented but is just an outline of what it might look like.

**Comment by matootie** [comment]
Since this solution will return some sort of error response any time you've already seen the quotes it wants to give you, we should implement an automatic retry in the front-end so it will send up to 5 or 10 requests spaced out a half or quarter of a second apart so that it's less likely to show you a "There are no quotes ready for you, come back later!" screen if you got unlucky and the system wanted to give you something you've already seen.

**Comment by bendurston** [comment]
I like this solution. To address the automatic retry,  could we not just call `SRANDMEMBER` with a count of say 5? 

Also I know you mentioned that the code above is just an example but we should keep in mind that if `num_quotes > num_seen` only by 1 then we should return "Not enough quotes, come back later" since it wont be able to find two new quotes. I just wanted to address this case :+1:

**Comment by nana-boateng** [comment]
@matootie For the solution you wrote O(2), did you mean O(n^2) or O(2^n) or just straight up O(1)?

When it comes to refetching in the frontend, react-query comes with tooling for that so no problem.

**Comment by matootie** [comment]
> For the solution you wrote O(2), did you mean O(n^2) or O(2^n) or just straight up O(1)?

Anywhere where I wrote O(2) is because the operation itself runs O(1), but needs to be done once for each quote so it's effectively O(2). I know this is pretty much negligible, but I wanted to write it regardless to be clear that the operation needs to be run twice.

**Comment by nana-boateng** [comment]
Oh then that doesn't sound bad at all. I like the idea
