### ISSUE TITLE
Create voting ranking system

### ISSUE THREAD

**Issue by bendurston** [yoiksoft/philosopher#2]
Currently when a vote is submitted, the quote's score increments by one. This needs to change to have a level playing field for quotes.

**Comment by matootie** [comment]
I'll consolidate the score calculation in code to it's own utility function, where it will take the existing score of the two quotes that are compared as two arguments, and it will be expected to return an integer representing the amount to increment for the winner.

```python
def calculate_winnings(winner_score, loser_score):
  num_to_add_to_winner = 1

  # Calculate winnings based off of existing scores.

  return num_to_add_to_winner
```
